#!/bin/bash
# ArtOnly Weekly List Article: June 22, 2026
# Post: the-week-in-music-june-22-2026
# Generated by scheduled agent

set -e
cd /home/dh_yadmw3
echo "=== ArtOnly Weekly List Deploy: $(date) ==="

SLUG="the-week-in-music-june-22-2026"
TITLE="Seven Artists Worth Your Time This Week"
IMG_DIR="artonly.io/assets/images/artists"

# =====================================================================
# Step 1: Copy hero image from Tierra Whack (most striking post of week)
# =====================================================================
echo "--- Copying hero image from tierra-whack-whacks-museum ---"
if [ -f "$IMG_DIR/tierra-whack-whacks-museum.jpg" ]; then
    cp "$IMG_DIR/tierra-whack-whacks-museum.jpg" "$IMG_DIR/$SLUG.jpg"
    SZ=$(wc -c < "$IMG_DIR/$SLUG.jpg")
    echo "Hero copied: $IMG_DIR/$SLUG.jpg ($SZ bytes)"
else
    echo "Source hero not found, downloading from Wikimedia"
    UA="Mozilla/5.0 (compatible; ArtOnly/1.0)"
    curl -s -L -A "$UA" \
      -o "$IMG_DIR/$SLUG.jpg" \
      "https://upload.wikimedia.org/wikipedia/commons/0/01/Tierra_Whack_MoMA_2018.jpg"
    SZ=$(wc -c < "$IMG_DIR/$SLUG.jpg" 2>/dev/null || echo 0)
    if [ "$SZ" -lt 5000 ]; then
        echo "ERROR: Hero image too small ($SZ bytes)"
        exit 1
    fi
    echo "Hero downloaded from Wikimedia: $SZ bytes"
fi

# =====================================================================
# Step 2: Publish post via API
# =====================================================================
echo "--- Publishing weekly list post ---"
python3 << 'PYEOF'
import urllib.request, json, sys, re

SLUG = "the-week-in-music-june-22-2026"
TITLE = "Seven Artists Worth Your Time This Week"

BODY = """The week of June 22, 2026 offered an unusual concentration of records worth taking seriously. Tierra Whack chose Juneteenth to release her most stripped-back project, handing the entire weight of the album to her writing alone. Micah Thomas released his fifth jazz album in New York, a record built around the idea that a musical phrase can be a complete object rather than the beginning of something larger. Olivia Rodrigo's third album, out ten days prior, continued to find the audience it deserves. And Future's pair of 2024 releases, still generating discussion in the places that care about this kind of thing, offer a picture of what an artist looks like when working at full capacity across two different modes simultaneously.

The seven artists below do not share a genre or an audience. Some have stadium careers and Grammy shelves. Some are building catalogs that will accumulate meaning slowly, over years and repeat listens. What they share is a quality of purpose, the sense that the record in question existed because it needed to, because there was something that could only be said in this specific form at this specific moment. That quality is not a guarantee of quality on its own. But it is a reliable filter. When an artist is clearly making the record they needed to make rather than the one the calendar required, the result tends to reward attention in ways that manufactured urgency never does. This was a good week to pay attention.

1. **Tierra Whack**

On Juneteenth 2026, Tierra Whack released WHACK'S MUSEUM, twelve tracks in twenty-seven minutes with no features and no visual scaffolding. After Whack World, with its sixty-second track format and its per-song visual universe, and after WORLD WIDE WHACK, the full-length debut that landed on Album of the Year lists at TIME and Rolling Stone, this mixtape removes everything except the pen. The wax motif running through the track titles, WAX PAPER, CANDLE WAX, EARWAX, announces the method: find every register a single syllable can occupy. She described this as her first true rap project. The writing backs that claim without hedging.

[Tierra Whack Strips the Spectacle and Lets Her Pen Do Everything](https://artonly.io/post/tierra-whack-whacks-museum)

2. **Olivia Rodrigo**

Released June 12, "you seem pretty sad for a girl so in love" is Rodrigo's third album and her most atmospheric. Producer Dan Nigro shapes a record that moves between brightness and a more inward deliberateness with more confidence than either SOUR or GUTS managed. The title names the album's subject directly: the gap between how love is supposed to appear from the outside and what it actually costs. Rodrigo has five Grammys and a stadium tour behind her. This record is quieter and more considered than anything that preceded it, and considerably richer as a result. The emotional intelligence was always there. The form finally matches it.

[Olivia Rodrigo Made the Contradiction Into the Point of the Whole Thing](https://artonly.io/post/olivia-rodrigo-you-seem-pretty-sad)

3. **Micah Thomas**

Thomas is a Juilliard-trained jazz pianist from Columbus, Ohio, who has spent years as a key voice in the Immanuel Wilkins Quartet. His fifth album Lucid, released June 19, is built around a specific compositional idea: that a musical phrase can function as a complete object, something held in the mind rather than developed across a longer arc. The quintet includes Wilkins on alto saxophone, Kalia Vandever on trombone, Thomas Morgan on bass, and Lesley Mok on drums. None of them announce themselves as the point. The record achieves genuine stillness without quietude, which is the harder and rarer accomplishment, and the one that will age best.

[Micah Thomas Finds the Still Point and Builds a Whole World Around It](https://artonly.io/post/micah-thomas-lucid)

4. **Future**

March 2024's We Don't Trust You with Metro Boomin set Spotify's record for the most streamed album in a single day that year, debuted at Billboard 200 number one, and ignited the most discussed rap conflict in recent memory via the Kendrick Lamar feature Like That. Six months later, Future released Mixtape Pluto with seventeen tracks and no guest credits, forty-four minutes of music made without the apparatus. The contrast between those two releases is the story. He has been running both modes, the enormous coordinated project and the solo record made for listeners paying close attention, since 2011. Understanding that structure is understanding the career.

[Future: The Record That Broke Spotify and the Mixtape That Ignored Everything](https://artonly.io/post/future)

5. **Hayley Kiyoko**

In 2015, Kiyoko made a music video for Girls Like Girls on twelve thousand dollars. Within a year it had ten million views. The girls like girls the album, released June 13, is the culmination of eleven years of building: a novel, a film opening June 19 through Focus Features that Kiyoko wrote and directed, and a fourteen-track album featuring Tegan and Sara, Young Miko, Joy Oladokun, and Gigi Perez. Three media formats built around one emotional premise. The original song treated queer first love as just love, with the same seriousness afforded to any other kind. The album inherits that directness and scales it without losing it.

[Hayley Kiyoko Completes the Story She Has Been Telling Since 2015](https://artonly.io/post/hayley-kiyoko-girls-like-girls-the-album)

6. **Ruel**

At twenty-three, Australian indie-pop artist Ruel has released a pair of companion albums that constitute one of contemporary pop's more structurally coherent statements about romantic love. Kicking My Feet, released in 2025, tracked the euphoric early phase of a relationship. Kicking My Feet and Screaming, released June 12 across twenty-one tracks and one hour, walks the same relationship through loss. Producers Joel Little, Kenny Beats, Julian Bunetta, and Dan Wilson each contributed without any single aesthetic dominating. The second album makes its full argument only in the context of the first. Together they document something most pop albums treat as a binary with unusual fidelity to the actual texture of the thing.

[Ruel Ends the Story He Started with Kicking My Feet and Screaming](https://artonly.io/post/ruel-kicking-my-feet-screaming)

7. **Leon Thomas III**

Leon Thomas III played Young Simba on Broadway at ten. He co-wrote SZA's Grammy-winning Snooze. He contributed to the Kanye West and Ty Dolla $ign album Vultures 1 in Florence. Between all of that, he released Mutt through EZMNY Records and Motown in September 2024: a Gold-certified R&B record that blended jazz, psychedelic soul, and rock, sent its title track to number 6 on the Hot 100, and collected Best R&B Album at the 68th Grammy Awards in February 2026. Best New Artist at the BET Awards followed in June 2025. The industry has been catching up to a timeline the music set years ago.

[Leon Thomas III Arrived on His Own Timeline](https://artonly.io/post/leon-thomas)

[download:/assets/images/artists/the-week-in-music-june-22-2026-social-9x16.jpg|Download Social Card]"""

# Verify no em-dashes or en-dashes
for dash in ['—', '–']:
    if dash in BODY:
        print(f"ERROR: dash character found: {repr(dash)}", file=sys.stderr)
        sys.exit(1)

clean = re.sub(r'\[(?:spotify|img|download):[^\]]+\]', '', BODY)
clean = re.sub(r'\[([^\]]+)\]\([^\)]+\)', r'\1', clean)
word_count = len(clean.split())
print(f"Body word count: {word_count}")

POST = {
    "action": "publish",
    "token": "ao-pub-Neverending48-2026",
    "slug": SLUG,
    "artist": "Allastair Voss",
    "image_url": "https://artonly.io/assets/images/artists/the-week-in-music-june-22-2026.jpg",
    "post": {
        "title": TITLE,
        "date": "2026-06-22",
        "category": "culture",
        "author": "Allastair Voss",
        "featured": False,
        "image": "/assets/images/artists/the-week-in-music-june-22-2026.jpg",
        "image_alt": "Tierra Whack at MoMA 2018",
        "image_position": "center 20%",
        "body": BODY
    }
}

data = json.dumps(POST).encode('utf-8')
req = urllib.request.Request(
    'https://artonly.io/api/publish.php',
    data=data,
    headers={'Content-Type': 'application/json'}
)
try:
    with urllib.request.urlopen(req, timeout=60) as r:
        resp = r.read().decode('utf-8')
        print(f"Publish response: {resp}")
        parsed = json.loads(resp)
        if not parsed.get('ok'):
            print(f"ERROR: publish failed: {resp}", file=sys.stderr)
            sys.exit(1)
        print("SUCCESS: weekly list post published")
except Exception as e:
    print(f"ERROR publishing: {e}", file=sys.stderr)
    sys.exit(1)
PYEOF

# =====================================================================
# Step 3: Generate social card
# =====================================================================
echo "--- Generating social card ---"
OMP_NUM_THREADS=1 python3 artonly.io/agent/make-social-card.py \
  "$SLUG" \
  "$TITLE" \
  culture
echo "Social card generated: $SLUG-social-9x16.jpg"

# =====================================================================
# Step 4: Validate post is live
# =====================================================================
echo "--- Validating post ---"
python3 artonly.io/agent/post-validator.py "$SLUG" || true
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://artonly.io/post/$SLUG")
echo "HTTP status artonly.io/post/$SLUG: $STATUS"

# =====================================================================
# Step 5: IndexNow
# =====================================================================
echo "--- Pinging IndexNow ---"
curl -s "https://api.indexnow.org/indexnow?url=https://artonly.io/post/$SLUG&key=5a4a5c1b5f124ccc9e6c4e5c5a4a5c1b"
echo ""
echo "IndexNow pinged: $SLUG"

# =====================================================================
# Step 6: Email summary to amosleblanc@gmail.com
# =====================================================================
echo "--- Sending summary email ---"
python3 artonly.io/api/gmail-send.py "amosleblanc@gmail.com" \
  "ArtOnly Weekly List: Seven Artists Worth Your Time This Week" \
  "Published today:

Seven Artists Worth Your Time This Week
https://artonly.io/post/the-week-in-music-june-22-2026

By Allastair Voss | 2026-06-22 | Category: culture

Covers:
1. Tierra Whack: WHACK'S MUSEUM (Juneteenth release)
2. Olivia Rodrigo: you seem pretty sad for a girl so in love
3. Micah Thomas: Lucid
4. Future: We Don't Trust You and Mixtape Pluto
5. Hayley Kiyoko: girls like girls the album
6. Ruel: Kicking My Feet and Screaming
7. Leon Thomas III: Mutt"
echo "Summary email sent to amosleblanc@gmail.com"

echo ""
echo "=== Weekly list deploy complete: $(date) ==="
echo "Live at: https://artonly.io/post/$SLUG"
